version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-hash-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-hash-{{ checksum "package.json" }}

      - run: yarn build
